name = "example-admin"
main = "src/index.ts"
compatibility_date = "2025-09-17"

# Bindings - IDs filled by Terraform outputs
[[d1_databases]]
binding = "DB"
database_name = "example_db"
database_id = "{{D1_DATABASE_ID}}"    # Replaced by CI/CD

[[kv_namespaces]]
binding = "PUBLISHED"
id = "{{KV_NAMESPACE_ID}}"             # Replaced by CI/CD

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "example-media"

[vars]
PROJECT_NAME = "example"
ADMIN_HOST = "admin.example.com"
CORS_ORIGIN = "https://example.com"