name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Non-secret config variables (set in repo Variables)
      CF_ACCOUNT_ID: ${{ vars.CF_ACCOUNT_ID }}
      CF_ZONE_ID: ${{ vars.CF_ZONE_ID }}
      D1_DATABASE_ID: ${{ vars.D1_DATABASE_ID }}
      KV_NAMESPACE_ID: ${{ vars.KV_NAMESPACE_ID }}
      R2_BUCKET: ${{ vars.R2_BUCKET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install Wrangler
        run: npm install -g wrangler@3

      - name: Display Config Summary
        run: |
          echo "Account: $CF_ACCOUNT_ID"
          echo "Zone: $CF_ZONE_ID"
          echo "D1 ID: $D1_DATABASE_ID"
          echo "KV ID: $KV_NAMESPACE_ID"
          echo "R2 Bucket: $R2_BUCKET"

      - name: Guard - Ensure placeholders still in repo version
        run: |
          set -e
          grep -R "{{D1_DATABASE_ID}}" app/wrangler.toml > /dev/null || (echo "Missing placeholder D1 in wrangler.toml" && exit 1)
          grep -R "{{KV_NAMESPACE_ID}}" app/wrangler.toml > /dev/null || (echo "Missing placeholder KV in wrangler.toml" && exit 1)

      - name: Prepare substituted copy
        run: |
          set -e
          mkdir -p _sub
          cp app/wrangler.toml _sub/wrangler.sub.toml
          sed -i "s/{{D1_DATABASE_ID}}/$D1_DATABASE_ID/g" _sub/wrangler.sub.toml
          sed -i "s/{{KV_NAMESPACE_ID}}/$KV_NAMESPACE_ID/g" _sub/wrangler.sub.toml
          # R2 Bucket handled by name not ID; ensure present
          grep "$R2_BUCKET" _sub/wrangler.sub.toml || echo "Note: R2 bucket name not referenced explicitly" 

      - name: Guard - Ensure no placeholders remain in substituted copy
        run: |
          set -e
          ! grep -R "{{D1_DATABASE_ID}}" _sub/wrangler.sub.toml || (echo "Substitution failed for D1" && exit 1)
          ! grep -R "{{KV_NAMESPACE_ID}}" _sub/wrangler.sub.toml || (echo "Substitution failed for KV" && exit 1)

      - name: Install SonicJS dependencies
        working-directory: app
        run: npm ci || npm install

      - name: Run database migrations
        working-directory: app
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cp ../_sub/wrangler.sub.toml wrangler.sub.toml
          wrangler d1 migrations apply popfizz_db --config wrangler.sub.toml

      - name: Build SonicJS application
        working-directory: app
        run: npm run build

      - name: Deploy SonicJS application
        working-directory: app
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cp ../_sub/wrangler.sub.toml wrangler.sub.toml
          wrangler deploy --config wrangler.sub.toml

      - name: Summary
        run: echo "Deployment complete. Single SonicJS worker deployed with integrated admin and frontend."
